### ISSUE TITLE
Capability of this toolkit

### ISSUE THREAD

**Issue by qianphhh** [vfitoolkit/vfitoolkit-matlab-replication#5]
Hello there! Is there any possible for this toolkit to solve lifecycle or OLG model with given ReturnToExitFn function of exogenous survival possibility?  Such as in every period an agent is facing an exogenous risk of entering into another form of value function (not zero), and also facing the probability of death.  An example is the model in "Fertility choice in a life cycle model with idiosyncratic uninsurable earnings risk" (Sommer, 2016). Thank you very much! Your toolkit really helps me a lot !!

**Comment by robertdkirkby** [comment]
I have copy pasted your question to discourse.vfitoolkit.com and am going to answer it there (I prefer to keep github to more narrow bug/code issues. The intended functionality is around opening and clossing issues.)
http://discourse.vfitoolkit.com/t/copied-from-github-can-you-go-to-different-value-fn-on-death/198

**Comment by robertdkirkby** [comment]
I have copy pasted your question to discourse.vfitoolkit.com and am going to answer it there (I prefer to keep github to more narrow bug/code issues. The intended functionality is around opening and clossing issues.)
http://discourse.vfitoolkit.com/t/copied-from-github-can-you-go-to-different-value-fn-on-death/198
