### ISSUE TITLE
Restuccia and Urrutia writeup

### ISSUE THREAD

**Issue by aledinola** [vfitoolkit/vfitoolkit-matlab-replication#7]
I was reading the model description pdf of Restuccia and Urrutia and I think there is a typo in the value function problem for young (age j=1). The continuation term has the expectation of V(.), but V is not defined anywhere else. I think it should be V_2

**Comment by robertdkirkby** [comment]
fixed. thanks!
https://github.com/vfitoolkit/vfitoolkit-matlab-replication/commit/a2bf66070be65d0d8839423d5796e1d7e5b614e1
