### ISSUE TITLE
Typo in Guerrieri-Lorenzoni pdf

### ISSUE THREAD

**Issue by aledinola** [vfitoolkit/vfitoolkit-matlab-replication#8]
I think there is a typo in the pdf document describing the model in Guerrieri and Lorenzoni (2017). 
The utility function should be increasing in leisure where leisure is defined as (1-n), and n denotes labor supply. So the term with (1-n) should come with a plus, not a minus, in front.

**Comment by robertdkirkby** [comment]
quite right, was typo, should be fixed now. Thanks for spotting!
